#define BUFFER_ALBEDO_PROPERTY COLOR0
#define BUFFER_SPECULAR_PROPERTY COLOR1
#define BUFFER_LIGHING_PROPERTY COLOR2
#define BUFFER_MISC_PROPERTY COLOR3
#define BUFFER_NORMAL COLOR4
#define BUFFER_NORMAL_EXACT COLOR5